/* Initial Migration
 * 06/07/2020
 */

CREATE TABLE SOURCE (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    LANGUAGE VARCHAR(6) NOT NULL,
    COUNTRY VARCHAR(30) NULL,
    STATUS VARCHAR(16) NOT NULL,
    DATE_CREATED DATE NOT NULL,
    DATE_INACTIVE DATE NULL
);

CREATE TABLE TAG (
    ID VARCHAR(36) PRIMARY KEY,
    TAG VARCHAR(36) NOT NULL,
    DATE_CREATED DATE NOT NULL
);

CREATE TABLE ARTICLE (
    ID VARCHAR(36) PRIMARY KEY,
    RELEASE_DATE DATE NOT NULL,
    SOURCE_ID VARCHAR(36) NOT NULL,
    CONTENT_ID VARCHAR(36) NOT NULL,
    TOPIC VARCHAR(16) NOT NULL,
    AUTHOR_ID VARCHAR(36) NULL,
    LANGUAGE VARCHAR(6) NOT NULL,
    DATE_CREATED DATE NOT NULL,

    /* Constraints */
    CONSTRAINT CONST_ART_FK_SOURCE_ID FOREIGN KEY FK_SOURCE_ID (SOURCE_ID) REFERENCES SOURCE(ID)
);

CREATE TABLE CONTENT (
    ID VARCHAR(36) PRIMARY KEY,
    ARTICLE_ID VARCHAR(36) NOT NULL,
    HEADER VARCHAR(100) NOT NULL,
    INTRODUCTORY VARCHAR(150) NOT NULL,
    CONTENT TEXT NOT NULL,

    /* Constraints */
    CONSTRAINT CONST_CONT_FK_ARTICLE_ID FOREIGN KEY FK_ARTICLE_ID (ARTICLE_ID) REFERENCES ARTICLE(ID)
);

CREATE TABLE IMAGE (
    ID VARCHAR(36) PRIMARY KEY,
    TITLE VARCHAR(50) NOT NULL,
    IMAGE BLOB NOT NULL
);

CREATE TABLE IMAGE_CONTENT_RELATION (
    ID VARCHAR(36) PRIMARY KEY,
    CONTENT_ID VARCHAR(36) NOT NULL,
    IMAGE_ID VARCHAR(36) NOT NULL,

    /* Constraints */
    CONSTRAINT CONST_FK_CONTENT_ID FOREIGN KEY FK_CONTENT_ID (CONTENT_ID) REFERENCES CONTENT(ID)
);

CREATE TABLE TAG_RELATION (
    ID VARCHAR(36) PRIMARY KEY,
    ARTICLE_ID VARCHAR(36) NOT NULL,
    TAG_ID VARCHAR(36) NOT NULL,
    DATE_CREATED DATE NOT NULL,

    /* Constraints */
    CONSTRAINT CONST_REL_FK_ARTICLE_ID FOREIGN KEY FK_ARTICLE_ID (ARTICLE_ID) REFERENCES ARTICLE(ID),
    CONSTRAINT CONST_REL_FK_TAG_ID FOREIGN KEY FK_TAG_ID (TAG_ID) REFERENCES TAG(ID)
);